name: horoscope_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  shared_preferences: ^2.0.5
  flutter_holo_date_picker: ^1.0.0-nullsafety.0
  auto_size_text: ^3.0.0-nullsafety.0
  cloud_firestore: ^1.0.3
  firebase_core: ^1.0.2
  stripe_payment: ^1.0.11
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: della
      fonts:
        - asset: assets/fonts/DellaRespira.ttf
